services:
  tasker-php:
    environment:
      DATABASE_URL: "mysql://root:tXDaKssxRrcphIQFLgJnxnRpJqKojQJF@interchange.proxy.rlwy.net:13286/railway"
      SERVER_NAME: ${SERVER_NAME:-localhost}
      TRUSTED_HOSTS: ^${SERVER_NAME:-example.com|localhost}|php$$
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
    build:
      context: .
      target: frankenphp_prod
    volumes:
      
./:/app:Z
./frankenphp/Caddyfile:/etc/caddy/Caddyfile:roZ
./frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:roZ
caddy_data:/data:Z
caddy_config:/config:Z
extra_hosts:
host.docker.internal:host-gateway
ports:
target: 80
  published: 80
  protocol: tcp
target: 443
published: 443
protocol: tcp
target: 443
published: 443
protocol: udp

volumes:
  caddy_data:
  caddy_config: